[profile.default]
src = "src"
out = "out"
script = "script"
test = "test"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_reports = ["CinaNFT"]

# Sepolia 部署配置
[profile.sepolia]
eth_rpc_url = "${SEPOLIA_RPC_URL}"

# 主网部署配置
[profile.mainnet]
eth_rpc_url = "${MAINNET_RPC_URL}"
